# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/document-processing"
site_name: DocumentProcessing
# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,_assetsApi]
exclude_navigation: [knowledge-base/*]

navigation:
## Common Start

## List your directory names and order here, like this:
    api:
        title: API Reference
        position: 100
    installation-and-deployment:
        title: Installation and Deployment
        position: 4
    upgrade:
        title: Upgrade
        position: 5
    distribution-and-licensing:
        title: Distribution and Licensing
        position: 6  
    integration:
        title: Integration
        position: 7
    libraries:
        title: Libraries
        position: 8	
    for-more-help:
        title: For More Help
        position: 10
    "*overview":
        title: Overview
        position: 1
    "*getting-started":
        title: Getting Started
        position: 2
    "*general-information":
        title: General Information
        position: 2
    "*changes-and-backward-compatibility":
        title: Changes and Backward Compatibility
        position: 3
    "*changes-and-backwards-compatibility":
        title: Changes and Backward Compatibility
        position: 3
    "*howto":
        title: How To
        position: 100
  
## RadWordsProcessing Start
    "*radwordsprocessing":
        title: RadWordsProcessing
    libraries/radwordsprocessing/model:
        title: Model
        position: 4
    libraries/radwordsprocessing/formats-and-conversion:
        title: Formats and Conversion
        position: 7
    libraries/radwordsprocessing/editing:
        title: Features
        position: 5
    libraries/radwordsprocessing/concepts:
        title: Concepts
        position: 6
    libraries/radwordsprocessing/formats-and-conversion/docx:
        title: Docx
        position: 1
    libraries/radwordsprocessing/formats-and-conversion/rtf:
        title: Rtf
        position: 2
    libraries/radwordsprocessing/formats-and-conversion/html:
        title: Html
        position: 3
    libraries/radwordsprocessing/formats-and-conversion/pdf:
        title: Pdf
        position: 4	
    libraries/radwordsprocessing/formats-and-conversion/plain-text:
        title: Plain text
        position: 5
    libraries/radwordsprocessing/concepts/fields:
        title: Fields
        position: 0		
## RadSpreadStreamProcessing Start 
    "*radspreadstreamprocessing":
        title: RadSpreadStreamProcessing
    libraries/radspreadstreamprocessing/model:
        title: Model
        position: 3
    libraries/radspreadstreamprocessing/features:   
        title: Features
        position: 4
    libraries/radspreadstreamprocessing/features/styling:
        title: Styling
        position: 0
## RadSpreadProcessing Start
    "*radspreadprocessing":
        title: RadSpreadProcessing
    libraries/radspreadprocessing/working-with-workbooks:
        title: Workbooks
        position: 3
    libraries/radspreadprocessing/working-with-worksheets:
        title: Worksheets
        position: 4
    libraries/radspreadprocessing/working-with-rows-and-columns:
        title: Rows and Columns
        position: 5
    libraries/radspreadprocessing/working-with-cells:
        title: Cells
        position: 6
    libraries/radspreadprocessing/formats-and-conversion:
        title: Formats and Conversion
        position: 8
    libraries/radspreadprocessing/features:
        title: Features
        position: 7
    libraries/radspreadprocessing/formats-and-conversion/import-and-export-to-excel-file-formats:
        title: Excel File Formats
        position: 2   
    libraries/radspreadprocessing/formats-and-conversion/import-and-export-to-excel-file-formats/xls:
        title: Xls
        position: 1  
    libraries/radspreadprocessing/formats-and-conversion/import-and-export-to-excel-file-formats/xlsx:
        title: Xlsx
        position: 2          
    libraries/radspreadprocessing/formats-and-conversion/pdf:
        title: Pdf
        position: 3
    libraries/radspreadprocessing/formats-and-conversion/csv:
        title: Csv
        position: 4
    libraries/radspreadprocessing/formats-and-conversion/txt:
        title: Txt
        position: 5
        
    libraries/radspreadprocessing/features/charts:
        title: Charts
        position: 0
    libraries/radspreadprocessing/features/fill-data-automatically:
        title: Fill Data Automatically
        position: 1
    libraries/radspreadprocessing/features/formulas:
        title: Formulas
        position: 2
    libraries/radspreadprocessing/features/protection:
        title: Protection
        position: 3
    libraries/radspreadprocessing/features/styling:
        title: Styling
        position: 4
## RadPdfProcessing Start
    "*radpdfprocessing":
        title: RadPdfProcessing   
    libraries/radpdfprocessing/model:
        title: Model
        position: 4
    libraries/radpdfprocessing/features:
        title: Features
        position: 6
    libraries/radpdfprocessing/model/interactive-forms:
        title: Interactive Forms
    libraries/radpdfprocessing/model/interactive-forms/form-fields	:
        title: Form Fields
    libraries/radpdfprocessing/formats-and-conversion:
        title: Formats and Conversion
        position: 7
    libraries/radpdfprocessing/formats-and-conversion/pdf:
        title: Pdf
        position: 0
    libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider:
        title: PdfFormatProvider
        position: 1
    libraries/radpdfprocessing/formats-and-conversion/pdf/pdfstreamwriter:
        title: PdfStreamWriter
        position: 2
    libraries/radpdfprocessing/formats-and-conversion/plain-text:
        title: Plain text
        position: 0
    libraries/radpdfprocessing/editing:
        title: Editing
        position: 9
    libraries/radpdfprocessing/concepts:
        title: Concepts
        position: 5		
## RadZipLibrary Start
    "*radziplibrary":
        title: RadZipLibrary
    libraries/radziplibrary/features:
        title: Features
        position: 5
        
        
    knowledge-base:
        position: 100
        

## The application virtual path
baseurl: "/devtools/document-processing"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Google Sheet ID
ff-sheet-id: 1HHlD_amgJPEh0GFobTkhTb9WBL9YbcKaYmlq-fCJb14

# The google services configuration
google_tag_manager: GTM-6X92
google_analytics: UA-111455-1
gcs_engine: '001595215763381649090:dzdv3_di-fm'
gcs_api_key: 'AIzaSyC_1zrkB9jMkIDAJ6VBYGilbhOWEFZqQKA'

edit_repo_url: https://github.com/telerik/dpl-docs/edit/master
product: "Telerik Document Processing"
product_url: https://www.telerik.com/document-processing-libraries

# Available for names: 
platforms: ["UI for ASP.NET Core", "UI for ASP.NET MVC", "UI for ASP.NET AJAX", "UI for Blazor", "UI for WPF", "UI for WinForms", "UI for Silverlight", "UI for Xamarin",]
# in articles use as shown below: 
# platforms: netcore, mvc, ajax, blazor, wpf, winforms, silverlight, xamarin
platform: dpl
download: https://www.telerik.com/download-trial-file/v2-b/devcraft-ultimate
nav:
  "Demos": http://www.telerik.com/support/demos
  "About": http://www.telerik.com/devcraft
  "Pricing": https://www.telerik.com/telerik-document-processing#Editions

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://docs.telerik.com/devtools/document-processing/getting-started
-
  title: "Support Resources"
  links: 
    "Documentation": https://docs.telerik.com/devtools/document-processing/introduction
    "GitHub SDK Repository": https://github.com/telerik/document-processing-sdk
-   
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/telerik-document-processing
    "Blogs": https://www.telerik.com/blogs/.net
    "Document Processing Feedback Portal": https://feedback.telerik.com/Project/184
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

api_reference_url: "api/"

has_kb_portal: true

sdk_examples: "sdk.json"
sdk_repo_path: "https://github.com/telerik/document-processing-sdk/tree/master/"
sdk_cdn_path: "https://cdn.rawgit.com/telerik/document-processing-sdk/master/"

# Folders not supporting Silverlight:
non-sl-folders: ["radwordsprocessing", "radspreadstreamprocessing"]

## Do not edit below this line
skip_tabbed_code: true
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
